version: '3.9'
services:
  work_shifts:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: work_shifts
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
  db:
    image: mysql:5.7.22
    container_name: db
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: 'workshifts'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: ""
    volumes:
      - ./db:/var/lib/mysql
  test_db:
    image: keinos/sqlite3:latest
    container_name: test_db
